#!/bin/bash

wiseclear;

count=$(git rev-list origin/master --count --since='$(date +%Y-%m-%d) 00:00')
git status;
echo "";  
git cherry -v;
echo "";  
echo -e "\033[1;1m> Commits on Master today: $count \033[m";
echo "";  
if [ $1 == ""] ; then
	git log -3 --graph --pretty;		
else
	git log -$1 --graph --pretty;
fi

echo "";  
exit;
